remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jemoji

title: TSC Minecraft Website
description: The website for the TSC Minecraft server.
show_downloads: false
logo: /assets/img/logo.png

github:
  is_user_page: false
  is_project_page: false
